#default:
#  image: maven:3.9.9-eclipse-temurin-17
#  cache:
#    key: "maven-$CI_COMMIT_REF_SLUG"
#    paths:
#      - .m2/repository/
#      - target/

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true  

stages:
  - build
  - test

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository/
      - target/
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository/
      - target/
  script:
    - mvn $MAVEN_CLI_OPTS test